[package]
name = "uniffi-bindgen-react-native"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "uniffi-bindgen-react-native"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
